package lt.vu.mybatis.model;

import java.util.Date;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.DATE_OF_BIRTH
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.DATE_OF_BIRTH
     *
     * @return the value of PUBLIC.AUTHOR.DATE_OF_BIRTH
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for PUBLIC.AUTHOR.DATE_OF_BIRTH
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @return the value of PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @param name the value for PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.SURNAME
     *
     * @return the value of PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.SURNAME
     *
     * @param surname the value for PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}