package lt.vu.mybatis.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.CATEGORY
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ISBN
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.PAGE_COUNT
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer pageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.AUTHOR_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ID
     *
     * @return the value of PUBLIC.BOOK.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ID
     *
     * @param id the value for PUBLIC.BOOK.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.CATEGORY
     *
     * @return the value of PUBLIC.BOOK.CATEGORY
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.CATEGORY
     *
     * @param category the value for PUBLIC.BOOK.CATEGORY
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ISBN
     *
     * @return the value of PUBLIC.BOOK.ISBN
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ISBN
     *
     * @param isbn the value for PUBLIC.BOOK.ISBN
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.PAGE_COUNT
     *
     * @return the value of PUBLIC.BOOK.PAGE_COUNT
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getPageCount() {
        return pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.PAGE_COUNT
     *
     * @param pageCount the value for PUBLIC.BOOK.PAGE_COUNT
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.AUTHOR_ID
     *
     * @return the value of PUBLIC.BOOK.AUTHOR_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.AUTHOR_ID
     *
     * @param authorId the value for PUBLIC.BOOK.AUTHOR_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
}