package lt.vu.mybatis.model;

public class Copy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COPY.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COPY.BOOK_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COPY.LIBRARY_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer libraryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COPY.USER_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COPY.ID
     *
     * @return the value of PUBLIC.COPY.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COPY.ID
     *
     * @param id the value for PUBLIC.COPY.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COPY.BOOK_ID
     *
     * @return the value of PUBLIC.COPY.BOOK_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COPY.BOOK_ID
     *
     * @param bookId the value for PUBLIC.COPY.BOOK_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COPY.LIBRARY_ID
     *
     * @return the value of PUBLIC.COPY.LIBRARY_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getLibraryId() {
        return libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COPY.LIBRARY_ID
     *
     * @param libraryId the value for PUBLIC.COPY.LIBRARY_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setLibraryId(Integer libraryId) {
        this.libraryId = libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COPY.USER_ID
     *
     * @return the value of PUBLIC.COPY.USER_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COPY.USER_ID
     *
     * @param userId the value for PUBLIC.COPY.USER_ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}