package lt.vu.mybatis.model;

public class Library {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LIBRARY.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LIBRARY.ADDRESS
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LIBRARY.ID
     *
     * @return the value of PUBLIC.LIBRARY.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LIBRARY.ID
     *
     * @param id the value for PUBLIC.LIBRARY.ID
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LIBRARY.ADDRESS
     *
     * @return the value of PUBLIC.LIBRARY.ADDRESS
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LIBRARY.ADDRESS
     *
     * @param address the value for PUBLIC.LIBRARY.ADDRESS
     *
     * @mbg.generated Fri Mar 05 01:21:41 EET 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }
}